import type { Application } from '../types/application';
import type { Deployment } from '../services/firebaseService';
import type { Repository, DeploymentHistory } from '../types/gitops';
import type { Cluster } from '../services/firebaseService';

// Mock data for demonstration purposes when user is not logged in
export const mockApplications: Application[] = [
  {
    id: 'mock-app-1',
    name: 'Frontend Application',
    description: 'React-based frontend application',
    status: 'Running',
    replicas: 3,
    created: '2024-01-15T10:30:00Z',
    updated: '2024-01-20T14:45:00Z',
    namespace: 'production',
    image: 'frontend-app:v1.2.3',
    version: 'v1.2.3',
    environment: 'production',
    health: {
      status: 'healthy',
      lastCheck: '2024-01-20T14:45:00Z',
      uptime: 99.8,
      responseTime: 120,
      errorRate: 0.1,
    },
    metrics: {
      cpu: { current: 45, limit: 100, unit: 'm' },
      memory: { current: 256, limit: 512, unit: 'Mi' },
      network: { bytesIn: 1024000, bytesOut: 512000 },
      requests: { total: 15000, perSecond: 25, errors: 15 },
    },
    resources: {
      cpu: { request: '100m', limit: '200m' },
      memory: { request: '256Mi', limit: '512Mi' },
      storage: { size: '1Gi', type: 'standard' },
    },
    logs: [],
    vulnerabilities: [],
    tags: ['frontend', 'react', 'production'],
    owner: 'John Doe',
    team: 'Frontend Team',
  },
  {
    id: 'mock-app-2',
    name: 'Backend API',
    description: 'Node.js REST API service',
    status: 'Running',
    replicas: 2,
    created: '2024-01-10T09:15:00Z',
    updated: '2024-01-19T16:20:00Z',
    namespace: 'production',
    image: 'backend-api:v2.1.0',
    version: 'v2.1.0',
    environment: 'production',
    health: {
      status: 'healthy',
      lastCheck: '2024-01-20T14:45:00Z',
      uptime: 99.5,
      responseTime: 85,
      errorRate: 0.05,
    },
    metrics: {
      cpu: { current: 65, limit: 200, unit: 'm' },
      memory: { current: 512, limit: 1024, unit: 'Mi' },
      network: { bytesIn: 2048000, bytesOut: 1024000 },
      requests: { total: 25000, perSecond: 40, errors: 12 },
    },
    resources: {
      cpu: { request: '200m', limit: '400m' },
      memory: { request: '512Mi', limit: '1024Mi' },
      storage: { size: '2Gi', type: 'standard' },
    },
    logs: [],
    vulnerabilities: [],
    tags: ['backend', 'nodejs', 'api'],
    owner: 'Jane Smith',
    team: 'Backend Team',
  },
];

export const mockDeployments: Deployment[] = [
  {
    id: 'mock-deploy-1',
    applicationId: 'mock-app-1',
    applicationName: 'Frontend Application',
    version: 'v1.2.3',
    status: 'completed',
    environment: 'production',
    startTime: '2024-01-20T14:30:00Z',
    endTime: '2024-01-20T14:35:00Z',
    replicas: 3,
    namespace: 'production',
    image: 'frontend-app:v1.2.3',
    logs: [],
    metrics: {
      cpu: 45,
      memory: 256,
      network: 1024,
    },
  },
  {
    id: 'mock-deploy-2',
    applicationId: 'mock-app-2',
    applicationName: 'Backend API',
    version: 'v2.1.0',
    status: 'completed',
    environment: 'production',
    startTime: '2024-01-19T10:15:00Z',
    endTime: '2024-01-19T10:20:00Z',
    replicas: 2,
    namespace: 'production',
    image: 'backend-api:v2.1.0',
    logs: [],
    metrics: {
      cpu: 65,
      memory: 512,
      network: 2048,
    },
  },
];

export const mockClusters: Cluster[] = [
  {
    id: 'mock-cluster-1',
    name: 'Production Cluster',
    provider: 'AWS',
    region: 'us-west-2',
    status: 'active',
    nodes: 5,
    cpu: { total: 20, used: 12, available: 8 },
    memory: { total: 80, used: 45, available: 35 },
    storage: { total: 1000, used: 600, available: 400 },
    applications: 2,
    created: '2024-01-01T00:00:00Z',
    updated: '2024-01-20T14:45:00Z',
  },
  {
    id: 'mock-cluster-2',
    name: 'Staging Cluster',
    provider: 'AWS',
    region: 'us-east-1',
    status: 'active',
    nodes: 3,
    cpu: { total: 12, used: 6, available: 6 },
    memory: { total: 48, used: 24, available: 24 },
    storage: { total: 500, used: 200, available: 300 },
    applications: 1,
    created: '2024-01-05T00:00:00Z',
    updated: '2024-01-20T14:45:00Z',
  },
];

export const mockRepositories: Repository[] = [
  {
    id: 'mock-repo-1',
    name: 'frontend-app',
    url: 'https://github.com/company/frontend-app',
    branch: 'main',
    autoDeploy: true,
    status: 'Active',
    lastDeployed: '2024-01-20T14:30:00Z',
    environment: 'production',
    namespace: 'production',
    path: '/',
    syncInterval: 300,
    lastSync: '2024-01-20T14:30:00Z',
    commitCount: 150,
    deploymentCount: 25,
    created: '2024-01-01T00:00:00Z',
    updated: '2024-01-20T14:30:00Z',
  },
  {
    id: 'mock-repo-2',
    name: 'backend-api',
    url: 'https://github.com/company/backend-api',
    branch: 'develop',
    autoDeploy: false,
    status: 'Active',
    lastDeployed: '2024-01-19T10:15:00Z',
    environment: 'staging',
    namespace: 'staging',
    path: '/',
    syncInterval: 300,
    lastSync: '2024-01-20T12:15:00Z',
    commitCount: 200,
    deploymentCount: 30,
    created: '2024-01-01T00:00:00Z',
    updated: '2024-01-20T12:15:00Z',
  },
];

export const mockDeploymentHistory: DeploymentHistory[] = [
  {
    id: 'mock-history-1',
    repositoryId: 'mock-repo-1',
    repositoryName: 'frontend-app',
    commitHash: 'abc123def456',
    commitMessage: 'Update UI components',
    branch: 'main',
    author: 'John Doe',
    timestamp: '2024-01-20T14:30:00Z',
    status: 'success',
    duration: 300,
    environment: 'production',
    namespace: 'production',
    resources: {
      deployments: 1,
      services: 2,
      configMaps: 1,
      secrets: 0,
    },
    created: '2024-01-20T14:30:00Z',
  },
  {
    id: 'mock-history-2',
    repositoryId: 'mock-repo-2',
    repositoryName: 'backend-api',
    commitHash: 'def456ghi789',
    commitMessage: 'Add new API endpoint',
    branch: 'develop',
    author: 'Jane Smith',
    timestamp: '2024-01-19T10:15:00Z',
    status: 'success',
    duration: 300,
    environment: 'staging',
    namespace: 'staging',
    resources: {
      deployments: 1,
      services: 1,
      configMaps: 0,
      secrets: 1,
    },
    created: '2024-01-19T10:15:00Z',
  },
];

export const mockDashboardStats = {
  totalApplications: 2,
  runningApplications: 2,
  failedApplications: 0,
  totalReplicas: 5,
  averageCpuUsage: 55,
  averageMemoryUsage: 384,
  totalDeployments: 2,
  activeDeployments: 2,
  totalClusters: 2,
  activeClusters: 2,
}; 